### ISSUE TITLE
Update All Readme File To Markdown Files

### ISSUE THREAD

**Issue by kb1lqd** [FaradayRF/Faraday-Software#11]
For proper Github support update the readme files to .md files for viewing on Github.

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by kb1lqc** [comment]
The following Applications have been updated to readme.md

- [Telemetry](https://github.com/FaradayRF/Faraday-Software/blob/master/Applications/Telemetry/readme.md)
- [APRS](https://github.com/FaradayRF/Faraday-Software/blob/master/Applications/APRS/readme.md)
- [Simple Message](https://github.com/FaradayRF/Faraday-Software/blob/master/Applications/simplemessage/readme.md)
- [Device Configuration](https://github.com/FaradayRF/Faraday-Software/blob/master/Applications/deviceconfiguration/readme.md)

Closing
