### ISSUE TITLE
Create Basic Text Messaging Program

### ISSUE THREAD

**Issue by kb1lqd** [FaradayRF/Faraday-Software#130]
## Summary
Utilizing Python only create a basic text messaging program that allows transmission and reception of single text messages between two Faraday units. Data transfered can be unreliable (no retry if error). This should be a simple and quick stepping stone into getting a reliable data transfer program (auto retry-request).

##Git Branch
I created this GIT branch to develop the program: https://github.com/FaradayRF/Faraday-Software/tree/issue130

## Problem Explanation
General requirements:
* Text/Data transfer between two specific units
* Error detection should be implemented
* Error correction should not be implemented
* Restful interfaces provided

#### Software 
>Please include the branch or commit if known regarding what software was used if applicable

#### Hardware
Units used during development:
* SN: 13 (No GPS)
* SN: 12 (GPS)

# Supporting Information
>This is a handy spot to post any screenshots or file outputs in order to better support this issue. We want to keep the top of the ticket clutter-free as possible.

**Comment by kb1lqd** [comment]
I finished tonight up after pulling in old (but not pulled into master yet in PR's) developer tutorial text messaging program. It needs more cleaning but it is built on simple class objects and works! I modified to meet some basic .INI and other standards we've introduced since. I split the scripts into TX and RX.

BTW we are calling this HERMES as he is the mythical god of the messengers: https://en.wikipedia.org/wiki/Hermes


Below is a screengrab from tonights progress showing RF text transmission between two faraday units using only the basic command application RF forwarding functionality.
![hermes_31417-1](https://cloud.githubusercontent.com/assets/339144/23892733/0443d200-0859-11e7-984a-b7ff2d6c07f8.gif)

**Comment by kb1lqd** [comment]
It should be noted that whenever using the simple command "RF Packet Forward" functionality that every packet must be directed to a specific unit. This doesn't allow general "Chat" with multiple devices.

A specific firmware "app" and UART/RF port must be created to implemented a "broadcast" ability. This is due to all commands being required to directly address the specific unit.

**Comment by kb1lqd** [comment]
@kb1lqc 

I created a basic RX Flask server that returns BASE64 encoded received messages from proxy:

![image](https://cloud.githubusercontent.com/assets/339144/24033487/51c110da-0aaa-11e7-8d25-b20c28fee431.png)

A simple script I wrote `rx_flask.py` using `requests` to decode and display the recieved text message:

![image](https://cloud.githubusercontent.com/assets/339144/24033524/9164b1ec-0aaa-11e7-8930-809460f480ff.png)

Here is a GIF of me using the simple implementation for receiver.

![hermes_31717-1](https://cloud.githubusercontent.com/assets/339144/24033810/f4d87096-0aab-11e7-97ee-213e107504c9.gif)

**Comment by kb1lqd** [comment]
Tonight's update made the receiver functionality even more Flask based and added a dedicated receiver script that queried queuesize and received waiting messages if items were in receiver queue.

TODO:
* Create transmitter module
 * Non-Intuitive since really TX/RX should be in same module and GET/POST interactions largely determine what Faraday does
* How to connect to two different local units for TX/RX full functionality? INI files?

**Comment by kb1lqd** [comment]
OK So I renamed the object and device info to generic names that don't imply a TX or RX only nature.

I also confirmed I was able to transmit using FLASK commands into the object!

![image](https://cloud.githubusercontent.com/assets/339144/24077647/ec2f8814-0c11-11e7-877e-c68a8749433c.png)


I am having trouble though figuring out how to make this modular so that a single file can create a class of two units and can transmit and receive to each other...

73ebd396145bfb444e90d272be0068bf76cd5849

**Comment by kb1lqd** [comment]
My user interface program implements FLASK:

![image](https://cloud.githubusercontent.com/assets/339144/24183999/e0f8313e-0e88-11e7-9b47-df082fbc5ccf.png)


I drew out a basic diagram of the current program architecture and the interfaces between them. 

![image](https://cloud.githubusercontent.com/assets/339144/24182864/de973dc4-0e81-11e7-86d3-c551a39673c1.png)

I believe I see a need to:

* Move all configuration to the "hermesflaskserver.py"
* Add a summary TX/RX class object to "hermesobject.py" tying TX/RX together
  * This should be independent of configuration and accept config from higher level?

**Comment by kb1lqd** [comment]
Arg! I was totally breaking the interface layer by having the application interface directly import a hermes object... That . Is. Bad.

![image](https://cloud.githubusercontent.com/assets/339144/24183942/8550b798-0e88-11e7-91a6-4ebfb1dc839b.png)

**Comment by kb1lqd** [comment]
**Commit:** 768dade9072f552218d7a543ede810d5e237d6e9

I figured it out! I realized I was close but not quite to the architecture that Proxy implements a similar input/output and all I needed to do was make a global dictionary that held TX/RX objects from hermesobject.py with keys related to the respective callsign/nodeid.

I used the `Callsign2COM` function (the name of that function makes no sense in this program) from proxy to parse and create the dictionary of configuration file units to dictionary objects.

![image](https://cloud.githubusercontent.com/assets/339144/24188550/fa3a57a6-0e9e-11e7-9aec-e544fd9e9e69.png)

The Flask API for getting a new message from the receiver class object from the hermes object is now abritrary to the object and allows for multiple unit objects `dictmsgobj` to be used.

![image](https://cloud.githubusercontent.com/assets/339144/24188974/826d411e-0ea0-11e7-85ae-b6d46d17d30d.png)


This allows me to use the Hermes Flask server like Proxy and address specific global (dictionary) hermes message objects (tx/rx interfaces) for multiple local units. This allows both a single unit to act as a transciever or multiple units to server transceiver functionality.

The TX and RX Flask user application examples are rough right now but clearly show intended FLASK operation for both TX and RX.

**TX**
![image](https://cloud.githubusercontent.com/assets/339144/24188744/ce9dc7f8-0e9f-11e7-9548-51df07767f9f.png)


**RX**
![image](https://cloud.githubusercontent.com/assets/339144/24188754/d5f1574a-0e9f-11e7-8f07-fc035ed8e4fa.png)

Transmitting shows the properly received "Hello World"

![image](https://cloud.githubusercontent.com/assets/339144/24188895/4331aac6-0ea0-11e7-831a-0096af1c7a5a.png)

**To-Do:**

I need to clean and organize the basic functionality after implementing the Flask interface.

**Update**

I updated TX to get user input.

![hermes_32217-1](https://cloud.githubusercontent.com/assets/339144/24189489/72e6184a-0ea2-11e7-93f5-328034ecf4d2.gif)

**Comment by kb1lqd** [comment]
@kb1lqc Here's a little proof showing it's Flask :) (using Postman):

![image](https://cloud.githubusercontent.com/assets/339144/24235912/9a4e9d5c-0f5c-11e7-9f52-1148981b18ad.png)

**Comment by kb1lqc** [comment]
One way to do this too is to have a worker in the background that saves to an SQLite db and has no knowledge of stations. Your queries with flask provide knowledge. This is how Telemetry tends to work. Not as useful for files but good for messages.

**Comment by kb1lqd** [comment]
Merged in #133
