### ISSUE TITLE
APRS Readme Erroneously Refers To Passcode Website

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/Faraday-Software#147]
## Summary
APRS [readme.md](https://github.com/FaradayRF/Faraday-Software/blob/master/Applications/APRS/readme.md) instructs users to obtain a passcode. The code currently generates the passcode automatically from the callsign rendering this obsolete. This section should be updated to indicate that the passcode is automatically generated.

## Problem Explanation
[generatePasscode()](https://github.com/FaradayRF/Faraday-Software/blob/master/Applications/APRS/aprs.py#L636) automatically creates a passcode and returns it to the APRS application to log into APRS-IS with. The documentation should be updated to indicate that the [callsign](https://github.com/FaradayRF/Faraday-Software/blob/master/Applications/APRS/aprs.sample.ini#L6) in aprs.ini is used to generate a passcode when properly configured with the operators callsign.

#### Software 
Faraday-Software (Python)

#### Hardware
None, this is a documentation issue

# Supporting Information
![image](https://cloud.githubusercontent.com/assets/331540/24743327/a9482b1e-1a62-11e7-9197-a2ed5b6e426d.png)

**Comment by markwiem** [comment]
Merge indicates that this issue can be closed. True?

**Comment by kb1lqc** [comment]
Thanks for the heads-up @markwiem you are correct.
