### ISSUE TITLE
Remote Commanding of MOSFET/HAB Timer Does Not Work

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/Faraday-Software#153]
## Summary
During #145 development it was observed that MOSFET and HAB Timer commands to remote Faraday stations does not work. These should be working.

## Problem Explanation
The following commands do not produce the expected results:
- [HAB Cut-down Event](https://github.com/kb1lqc/Faraday-Software/blob/simple_web_ui/Applications/SimpleUI/simpleui.py#L320)
- [Reset HAB Cut-down Timer](https://github.com/kb1lqc/Faraday-Software/blob/simple_web_ui/Applications/SimpleUI/simpleui.py#L324)
- [Disable HAB Cut-down Timer](https://github.com/kb1lqc/Faraday-Software/blob/simple_web_ui/Applications/SimpleUI/simpleui.py#L328)
- [HAB Reset Cut-down Idle](https://github.com/kb1lqc/Faraday-Software/blob/simple_web_ui/Applications/SimpleUI/simpleui.py#L332)

#### Software 
Software SimpleUI Branch application: https://github.com/kb1lqc/Faraday-Software/tree/simple_web_ui/Applications/SimpleUI

#### Hardware
>Let us know about what hardware you are using if applicable. This includes:
- Using Windows 10 on a Microsoft Surface Pro 4
- Normal Rev D1 Faraday radios

# Supporting Information
None

**Comment by kb1lqd** [comment]
Verified that local MOSFET cutdown works as intended:
![image](https://cloud.githubusercontent.com/assets/339144/25113896/97d42b66-23af-11e7-9cf9-d3a45a41dd83.png)

**Comment by kb1lqd** [comment]
Observing a local unit sending the RF command it is obviuos that there is a missing frame in the RF packet being sent. The callsign "K" is in the command position where RF remote command `9` should be. 

![image](https://cloud.githubusercontent.com/assets/339144/25113975/0b5b0758-23b0-11e7-99dc-c4f5e6bd4487.png)


Trying the remote LED ON command shows a valid `9` in the command byte after local parsing prior to RF transmissions:

![image](https://cloud.githubusercontent.com/assets/339144/25114007/363e45c0-23b0-11e7-8874-55aaade31498.png)

**Comment by kb1lqd** [comment]
OK I think I fixed it, @kb1lqc you deviated from your working implementations of remote commanding to do the MOSFET actions as if they were "special" when they are in fact not. Adding the local command `9` to send the packet over RF to a remote device looks to have solved the issue. I haven't tried this on a real remote unit (I don't have gear to test this MOSFET at the moment):

Modifying:

`command = faraday_cmd.CommandRemoteHABActivateCutdownEvent(remotecallsign, remotenodeid)`

to

`command = faraday_cmd.CommandLocal(9, faraday_cmd.CommandRemoteHABActivateCutdownEvent(remotecallsign, remotenodeid))`
Looks to have created the proper packet as I'd expect, @kb1lqc please confirm this solves the issue and roll into all remote command as needed (looks like only the MOSFET ones are missing it).

![image](https://cloud.githubusercontent.com/assets/339144/25114211/d06cd296-23b1-11e7-86d0-ce4e4f7e492d.png)


![image](https://cloud.githubusercontent.com/assets/339144/25114255/2fd371f4-23b2-11e7-87d8-6c8152cca912.png)

**Comment by kb1lqc** [comment]
Ok I'll test. Wow yeah I just read through code and found what appeared to be correct since the remote MOSFET wasn't in any examples I could find. I'll test.

P.S. Instead of images (or in addition to), you can link directly to the line 😉

**Comment by kb1lqc** [comment]
OK most seem to work @kb1lqd. I think I need to check the Idle timer and actually look at the MOSFET resistance during firing with a multimeter. However, just by states I can tell the command of HAB timers seems to be working and the MOSFET firing also seems to work!

![simpleui-remotehabmosfet](https://cloud.githubusercontent.com/assets/331540/25114806/45c5627a-23b6-11e7-85b6-c5543d674ca6.gif)

**Comment by kb1lqc** [comment]
Yes @kb1lqd this is odd or at least not what I expect.

When the MOSFET hasn't fired yet but timer is counting and I send an Idle... nothing happens.
![simpleui-remotehabmosfet-idletest2](https://cloud.githubusercontent.com/assets/331540/25114920/3cc5c402-23b7-11e7-8dbb-5381b4492837.gif)

Yet when I have fired the MOSFET (STATE = 255) and set Idle the Cut-Down State returns to 0 without anything else changing.
![simpleui-remotehabmosfet-idletest](https://cloud.githubusercontent.com/assets/331540/25114939/585eb53e-23b7-11e7-87da-34bff826acca.gif)

**Comment by kb1lqd** [comment]
That's exactly what I'd expect. Idle set is only used to set the state
machine into idle 0, most likely from idle 255 post firing. If your in 0
and command idle 0 you'll do nothing...

This is so you can reset from post fire 255 and catch a future firing
without needing to catch telem as it happens.

**Comment by kb1lqc** [comment]
Closing this as @kb1lqd pointed out I had used the commands incorrectly implemented. This is fixed in the branch the issue was found in.

https://github.com/kb1lqc/Faraday-Software/tree/simple_web_ui

Specifically the commit it was fixed in:
407f8bec3d461c158ad30dc17d1545515f7a1685
