### ISSUE TITLE
Prerequisite Spelled Wrong in APRS Documentation

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/Faraday-Software#165]
## Summary
"prerequisit" is incorrectly spelled in the APRS documentation [readme.md](https://github.com/FaradayRF/Faraday-Software/blob/master/Applications/APRS/readme.md). Simple update the spelling!

## Problem Explanation
N/A

#### Software 
N/A

#### Hardware
N/A

# Supporting Information
![image](https://cloud.githubusercontent.com/assets/331540/25168745/87ef4d12-2499-11e7-84c3-5c5c528d63f6.png)

**Comment by morrme** [comment]
@kb1lqc  I have just submitted a PR fixing this.
