### ISSUE TITLE
Create Proxy Log File Repository

### ISSUE THREAD

**Issue by kb1lqd** [FaradayRF/Faraday-Software#168]
## Summary
With the merging of #152 proxy now has the ability to "replay" prior recorded data. This is especially useful for developers without Faraday hardware or when testing specific situations. A repository on GitHub should be created to allow the community access to known good logs for playback.

## Problem Explanation
Create a log folder (and update contributions guide) for proxy playback recordings. This should include known good logs of things such as:
* General single unit local telemetry
* Multiple local unit telemetry
* Local and remote unit telemetry

The repository should clearly identify what the log file contains and is inteded to be used for.

#### Software 
N/A
#### Hardware
N/A

# Supporting Information

**Comment by kb1lqc** [comment]
Closing as we have completed this!
