### ISSUE TITLE
"Queue" Misspelled in Proxy readme.md

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/Faraday-Software#170]
## Summary
Queue misspelled as "qeue" in the Proxy application readme.md. This should be updated. It is highly suggested and appreciated to read through and find any other spelling or grammar errors.

## Problem Explanation
Proxy [readme.md](https://github.com/FaradayRF/Faraday-Software/blob/master/Proxy/readme.md)

#### Software 
N/A

#### Hardware
N/A

# Supporting Information
![image](https://cloud.githubusercontent.com/assets/331540/25268091/43a7ada4-262c-11e7-9753-221554bc8765.png)

**Comment by morrme** [comment]
@kb1lqc ready :nerd_face:
