### ISSUE TITLE
Proxy/Telemetry/APRS Error Long Duration Raspberry Pi 3

### ISSUE THREAD

**Issue by kb1lqd** [FaradayRF/Faraday-Software#190]
## Summary
While letting a Raspberry Pi 3 run the noted commit run for ~1.5 days it seems that APRS.py errored. Telemetry and Proxy remained running although after a restart of APRS.py only ARPS uploading restarted for only 1 of two units. 1 Unit is local while the other is remote (RF).

## Problem Explanation

This long duration test of proxy, telemetry, and APRS scripts ran for over a day but failed due to what looks like unexpected data/format from unit `KB1LQD-25`. The error crash APRS.py, I was logging proxy logs and telemetry logs. Restarting the APRS.py script refreshed `KB1LQD-2` but not `KB1LQD-15`. 

#### Software 

Running Master:

commit 3d91490717f4c8782f8ebe86c07c8b873fa271e3
Merge: 421aa2f 84c67be
Author: Reilly Grant <reillyeon@qotw.net>
Date:   Mon Apr 24 00:23:35 2017 -0700

    Merge pull request #174 from FaradayRF/kb1lqc-proxylink-2

    Fixed readme.md Proxy folder links
#### Hardware
* Faraday REV D1 - SN:18 (Local)
* Faraday REV D1 - SN:13 (Remote - powered by external USB HUB)

# Supporting Information

## Logs

* Proxy = `logs.db`
* Telemetry = `telemetry.db`

[Logs.zip](https://github.com/FaradayRF/Faraday-Software/files/963578/Logs.zip)

### Proxy
![image](https://cloud.githubusercontent.com/assets/339144/25516699/e0f32858-2ba0-11e7-821b-b9240d60b6e3.png)

### Telemetry
![image](https://cloud.githubusercontent.com/assets/339144/25516701/e44ac3c6-2ba0-11e7-993d-1178f228f124.png)

### APRS

![image](https://cloud.githubusercontent.com/assets/339144/25516689/d5df1d5a-2ba0-11e7-851a-a3201d4774dd.png)

APRS Stopped working randomly after many hours left running (~1.5 days). It seems like only APRS died.

I restarted APRS:
![image](https://cloud.githubusercontent.com/assets/339144/25516643/92ffc1ce-2ba0-11e7-909f-9ada33361c02.png)

A little longer later…

![image](https://cloud.githubusercontent.com/assets/339144/25516659/a8a30130-2ba0-11e7-8e48-92bc7ae81a2e.png)

KB1LQD-2 seems to have restarted but -25 did not… must be the one erroring:

![image](https://cloud.githubusercontent.com/assets/339144/25516662/af3e1cd2-2ba0-11e7-863b-b19991b21b02.png)

**Comment by kb1lqc** [comment]
So is the remote unit even logging into telemetry sqlite db anymore?

**Comment by kb1lqd** [comment]
I'm not sure, looks like -25 is the last log in the system but only -2 is being updated after APRS.py restart...

**Comment by kb1lqd** [comment]
See the log file I posted? @kb1lqc

**Comment by kb1lqc** [comment]
Per `telemetry.db` in the attached `log.zip` with this ticket the problem is with GPSALTITUDE **KB1LQD-25** and occurred at or around EPOCH 1493345336.83446 (Thursday, April 27, 2017 7:08:56 PM GMT-7:00 DST) which is on`KEYID` = 14456

> GPSALTITUDE = 17.43.90

This is causing the float error since it is not a float as we expect.

## Problems

1. This should not error but should simply raise an exception
2. This is likely firmware not software, however there's room for it to be `Telemetry`

It appears as though the GPS Altitude of 17.4 was appended with a 3.90 to create 17.43.90 we see. notice the previous GPS Altitudes for `KB1LQC-25`:

![image](https://cloud.githubusercontent.com/assets/331540/25517445/4ffd73fe-2ba4-11e7-88e9-b2df64435ef6.png)

@kb1lqd I believe it's firmware because I've seen the firmware do this however I guess it could be software since we really should be checking GPS Altitude as a float prior to inserting it into the database. However it is converted to a string so there is a change we are messing up in `Telemetry`.

**Comment by el-iso** [comment]
Any idea where the 3.90 came from? It seems like knowing that might help isolate the bug. 
Also, could this be a problem with formatting json (a missing comma in the json or something like that)?  Just tossing in my thoughts... @kb1lqd @kb1lqc

**Comment by kb1lqd** [comment]
Having only restarted APRS.py on thursday after the crash and not seeing `KB1LQD-25` which is the local unit to the raspberry pi when restarting it seems like a check-in tonight shows the station back!

![image](https://cloud.githubusercontent.com/assets/339144/25562868/72917616-2d45-11e7-8f0e-b4d0e9888803.png)

I'm not sure why it is now working but it's a good clue that it cleared itself after the restart, eventually. 

@el-iso I'm not sure yet but I think this is a question of both:
* Where did the invalid data/format come from
* Should we be protecting against a hard crash in APRS.py or is this a situation that should never happen and crashing is a good indicator to fix it.

**Comment by kb1lqd** [comment]
Interesting, in `KB1LQD-2` shows active VALID position data to APRS-IS but the last valid telemetry data to APRS-IS is over a day old! Weird!
![image](https://cloud.githubusercontent.com/assets/339144/25562901/f977ee12-2d45-11e7-9744-b284b37f0cd3.png)

It seems like `KB1LQD-25` is updating both OK:

![image](https://cloud.githubusercontent.com/assets/339144/25562905/0edb7526-2d46-11e7-9a3d-06604319df89.png)

**Comment by kb1lqc** [comment]
The last telemetry packet from `KB1LQD-2` was:

`2017-04-29 02:34:56 CDT: KB1LQD-2>GPSFDY,QAR,KB1LQD-25,qAS,KB1LQD:T#525,149,147,140,000,001,00000000`

![image](https://cloud.githubusercontent.com/assets/331540/25564005/1aaaf38c-2d5e-11e7-88e2-dfc8dbd4f028.png)

Seems spotty/weird in your RAW packet stream. Unsure if whether the APRS application is not sending it or APRS-IS is ignoring them...

**Comment by kb1lqd** [comment]
PR #273 looks to have fixed this issue in conjunction with PR #271.
