### ISSUE TITLE
Add `--start` option control to `faraday-proxy`

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/Faraday-Software#228]
## Summary
Make command line option `--start` be required to actually start the proxy server. Allow configuration to occur without the `--start` option but exit the program upon completion.

## Problem Explanation
N/A

#### Software 
Faraday Software Master

#### Hardware
N/A

# Supporting Information
This was implemented in device-configuration per PR #219 and it's been very useful. So much so we are rolling it out to all other applications.

**Comment by kb1lqd** [comment]
Implemented in #234
