### ISSUE TITLE
Telemetry: Odd ADC Behavior When Plotting Data

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/Faraday-Software#23]
As shown below, there's an obvious "tick" when plotting ADC data. This could be a poorly implemented parser or it could actually be in the Firmware @kb1lqd. If nothing about the ADC code changed since the Balloon flight then it's probably the software. I could also use the balloon software to cross check this firmware.

![image](https://cloud.githubusercontent.com/assets/331540/19466206/3d8f7be0-94be-11e6-8d55-7f1707b0da0d.png)

Not critical to fix right now (10/17/2016) but we should get onto this when looking at ADC firmware or telemetry.
- [ ] Cross-checked balloon flight (8/2016) telemetry and proxy software

**Comment by kb1lqd** [comment]
@kb1lqc I'd check with the as-flown HAB firmware. I don't believe I've changed anything (other than fixing the temperature char sign issue).

**Comment by kb1lqc** [comment]
This issue could be Firmware as noted in https://github.com/FaradayRF/Faraday-Firmware/issues/15

_I'll keep this ticket open until the firmware ticket closes._

**Comment by kb1lqc** [comment]
Just closed https://github.com/FaradayRF/Faraday-Firmware/issues/15#issuecomment-277561232 which addresses a similar if not the same issue. We will see if it was fixed. No root cause. Need to get better about systematically handling these issues in the future. Just @kb1lqd and I right now traveling 1,000,000 mph!
