### ISSUE TITLE
Create a HAB Balloon filler tool.

### ISSUE THREAD

**Issue by kb1lqd** [FaradayRF/Faraday-Software#263]
Determine the best method to fill and measure the balloon for the Faraday HAB mission. Create any PCBA's and mechanical that are needed. Document the tool use.

**Comment by kb1lqc** [comment]
Honestly this is probably worth the money and time... Includes a simple lift scale too:
https://www.highaltitudescience.com/products/3-cm-max-safe-inflator

**Comment by kb1lqc** [comment]
Can we close this? I'm not sure it's worth developing our own...

**Comment by kb1lqc** [comment]
@kb1lqd I feel that even when we go and do our own balloon we should just buy one... not really worth building. Want to close it?

**Comment by kb1lqd** [comment]
CLosing due to scope reduction and we'll just buy one of these as needed.
