### ISSUE TITLE
APRS Longitude Dropping Leading Zero

### ISSUE THREAD

**Issue by kb1lqd** [FaradayRF/Faraday-Software#46]
When using the APRS program in Massachussetts it was realized that the APRS server upload was not accepting the station data, packets were received but APRS.fi was showing currupted packets.

Investigation showed good receive data but the APRS conversion prior to upload shows the leading 0 of the longitude getting dropped. I added debug code to print lat/lon and verified.

**Comment by kb1lqd** [comment]
Confirmed by forcing a debug GPS longitude of my location with the leading zero, it worked:

![image](https://cloud.githubusercontent.com/assets/339144/21460480/a69b0488-c8fd-11e6-8995-4ffa0185e26a.png)

`07122.99` was being truncated to `7122.99`.

**Comment by kb1lqd** [comment]
![image](https://cloud.githubusercontent.com/assets/339144/21460632/4fb385e4-c8ff-11e6-8bb8-7d08c2dd0aa4.png)


Valid APRS.fi uploading. Method of the new string formatting found here: http://stackoverflow.com/a/17118161

**Comment by kb1lqd** [comment]
@kb1lqc do you have any concerns with this solution of the noted bug? I did modify the formatting you were performing but seems like the reasonable solution.

**Comment by kb1lqd** [comment]
Seems like my correction didn't catch all situations correctly, the leading 0 on the LAT not liked?

![image](https://cloud.githubusercontent.com/assets/339144/21463943/76cb112a-c926-11e6-8b5d-8fff3668d5cd.png)

**Comment by kb1lqc** [comment]
Whew is that n coming from after the W? That's causing this now. Either in my code or lower down in your firmware.Try tracing the lat/long as well as lat dir and long dir to make sure that n isn't in there.---- On Fri, 23 Dec 2016 15:42:53 -0800  Brenton Salmi<notifications@github.com> wrote ----Seems like my correction didn't catch all situations correctly, the leading 0 on the LAT not liked?   —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by kb1lqc** [comment]
Whew is that n coming from after the W? That's causing this now. Either in my code or lower down in your firmware.

 

Try tracing the lat/long as well as lat dir and long dir 

 

---- On Fri, 23 Dec 2016 15:42:53 -0800 Brenton Salmi<notifications@github.com> wrote ----

 

Seems like my correction didn't catch all situations correctly, the leading 0 on the LAT not liked?

 <https://cloud.githubusercontent.com/assets/339144/21463943/76cb112a-c926-11e6-8b5d-8fff3668d5cd.png>

**Comment by kb1lqc** [comment]
Yeah so no longer in Vietnam looking at code on my iPhone trying to figure this out. The "n" after the W in the telemetry packet is good. That is the APRS symbol. Need to track this one down. Something is causing the uncompressed location bug.

**Comment by kb1lqc** [comment]
Pretty sure I fixed this in #75 . When that one closes let's see if it also gets this issue.

**Comment by kb1lqc** [comment]
Per @kb1lqd comments and testing on https://github.com/FaradayRF/Faraday-Software/pull/77 this issue is complete. Closing!
