### ISSUE TITLE
First Proxy Data To Unit Fails

### ISSUE THREAD

**Issue by kb1lqd** [FaradayRF/Faraday-Software#50]
**Issue**
I've noticed that after starting Proxy the first data sent to the unit always fails. Retrying the transmission of the data is successful as is all future transmissions (to my knowledge).

The program first using proxy displays this error:
![image](https://cloud.githubusercontent.com/assets/339144/21972132/16ad46fc-db6c-11e6-825a-ec00aacb5dc2.png)

I see proxy log:
![image](https://cloud.githubusercontent.com/assets/339144/21972127/081d1608-db6c-11e6-99a0-0572e4bbc65e.png)

**Proper Operation**
Proper operation would not cause error on the first data transmission to the unit. Although I have not debug breakpointed or scope captured on the Faraday device to confirm I have no reason to believe data is being transmitted to the unit on first attempt. It looks as if Proxy can't handle the first lookup of the unit correctly.

**Comment by kb1lqd** [comment]
Confirmed bug as run in tutorial with a "fresh" proxy connection:

![image](https://cloud.githubusercontent.com/assets/339144/23107144/ae22c48e-f6ac-11e6-806a-4a17ab6c22bf.png)


https://github.com/FaradayRF/Faraday-Software/tree/Developer_Tutorial_Update_2-18-17/Tutorials/Python_Developer_Tutorials/foundation/Commanding-Local

Running the tutorial a second time produces nominal operation.

**Comment by kb1lqc** [comment]
This is related to #60

**Comment by kb1lqc** [comment]
@kb1lqd Can you double-check that this was fixed?

**Comment by kb1lqc** [comment]
Actually I just checked it @kb1lqd and it works without issue. Closing this ticket.
