### ISSUE TITLE
Add Contributors Guide

### ISSUE THREAD

**Issue by kb1lqd** [FaradayRF/Faraday-Software#6]
A contributors guide is needed to help contributors understand the standards for pulling back into the master. Although all the code is not currently compliant the high level overview is:
- Python follows PEP8 standards for code formatting
- Ignore binaries (i.e. .pyc files)
- Follows our layering practices with IO at an interface (i.e. Flask) for applications with the UI abstracted to another level.

**Comment by kb1lqd** [comment]
http://blog.technicallyliving.com/2013/11/creating-a-gitignore-file-in-windows/

https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by kb1lqc** [comment]
@kb1lqd is this https://github.com/FaradayRF/Faraday-Software/blob/master/CONTRIBUTING.md complete?

**Comment by kb1lqc** [comment]
Yeah actually this is complete! I totally missed your tagging of me and randomly came upon this. Closing.
