### ISSUE TITLE
Device Configuration - Add "readconfig.py"

### ISSUE THREAD

**Issue by kb1lqd** [FaradayRF/Faraday-Software#88]
It's become clear that when dealing with multiple units there needs to be an easy way to query the units information without programming it first. This issue enhancement is asking to add a file like simpleconfig.py that only reads the currently connected units configuration.

![image](https://cloud.githubusercontent.com/assets/339144/23098293/30d19c6a-f5ff-11e6-90c6-2d8e8a563f6a.png)

**Comment by kb1lqc** [comment]
I believe this was already completed right @kb1lqd ?

**Comment by kb1lqc** [comment]
This was completed with #141
