### ISSUE TITLE
Telemetry .upper() in Stations Causing APRS to not start

### ISSUE THREAD

**Issue by kb1lqd** [FaradayRF/Faraday-Software#91]
I noticed that APRS will not start with the latest telemetry.py update. The APRS window crashes and programs fails to start.

![image](https://cloud.githubusercontent.com/assets/339144/23107528/77a52ad0-f6b3-11e6-84c3-196350b4bdf0.png)

Bug tracked to the "getStations()" telemetry call that APRS tries to use.

![image](https://cloud.githubusercontent.com/assets/339144/23107526/6fd5eb1e-f6b3-11e6-8c5e-102b4a89eff0.png)

Telemetry.py prompt reports this failure: 
![image](https://cloud.githubusercontent.com/assets/339144/23107547/d26a641c-f6b3-11e6-9442-4ca40dee491e.png)

I printed the callsign variable at line 357 and it was `NoneType`

I believe this is failing because the `.upper()` assumes a string but got `None`. This was recently merged and this situation (using APRS) probably wasn't vetted properly.

**Actions**

I'm going to push a simple pull request to remove the .upper() to allow the program to work. This may cause failure if the user doesn't enter their callsign in all UPPERCASE in the configuration(s).

**Comment by kb1lqd** [comment]
Removing .upper() allows startup but no APRS upload yet. Waiting for GPS lock on this unit:

![image](https://cloud.githubusercontent.com/assets/339144/23107598/c09b778e-f6b4-11e6-822c-d35b798419eb.png)

I'm going to try to verify if I can solve this quickly without removing .upper() since it seems the getStations() isn't getting callsign first. The program is still failing non-gracefully.

**Comment by kb1lqc** [comment]
Not sure if actually caused by upper() as you should a I'll be getting a callsign. Is something causing the callsign not to actually be in the dictionary?

**Comment by kb1lqd** [comment]
@kb1lqc 

Well I think a different issue is that Telemetry/APRS fails hard if it doesn't see data. It should fail gracefully/not stop.

Tracking this down in aprs.py:

![image](https://cloud.githubusercontent.com/assets/339144/23107626/4bf3f07c-f6b5-11e6-9884-402f4c168dad.png)

![image](https://cloud.githubusercontent.com/assets/339144/23107634/60f9e4fe-f6b5-11e6-938e-f2847aebd48f.png)

Leads me to telemetry.py:

Looks like default if no URL argument supplied is `None`?

![image](https://cloud.githubusercontent.com/assets/339144/23107645/7de5b3a4-f6b5-11e6-9a71-f7c14f6b615e.png)

Immediately below this is the failing code:

![image](https://cloud.githubusercontent.com/assets/339144/23107648/8f3e61aa-f6b5-11e6-8362-bdd4cdb6ca98.png)

**Comment by kb1lqd** [comment]
@kb1lqc 
Hmmm... I placed the .upper() back in and ran telemetry (this time with a working and valid GPS signal) and the program doesn't quit but does not log into the APRS servers to upload:

![image](https://cloud.githubusercontent.com/assets/339144/23107781/6fc980f4-f6b8-11e6-9f64-0c040f15494f.png)

**Comment by kb1lqd** [comment]
Note: I have not yet been able to update APRS location, I was 1-2 days ago.

Interesting:

**APRS Configuration ROTATE.APRS.NET**

Although it failed originally to cause this ticket in this default APRS server it no longer exhibits the .upper() failure noted when configured to use this server.

**APRS Configuration SECOND.APRS.NET**
When using this server (prior commits) and correct port the .upper() bug reappears.
![image](https://cloud.githubusercontent.com/assets/339144/23107832/4cfb82b0-f6b9-11e6-9361-0570a0283d87.png)

**Comment by kb1lqd** [comment]
So APRS is failing at line 93 which is the:

`results = r.json()`

![image](https://cloud.githubusercontent.com/assets/339144/23110106/7ffa0064-f6d3-11e6-9910-cbe0ca316374.png)

Notice that `url = "http://" + host + ":" + port + "/stations"` forms the GET request URL without any arguments? This is probably why they are being passed as "None." Although telemetry ( @kb1lqc ) telemetry should handle/fail gracefully in this situation we should avoid APRS from causing this condition in the first place.

**Comment by kb1lqd** [comment]
OK I think I have an idea of whats happening, I moved the telemetry.py parameters dictionary filling code into the try/except bock to fail softly.

![image](https://cloud.githubusercontent.com/assets/339144/23110525/f1d85ca0-f6d6-11e6-9027-479591b1bda1.png)

I also printed debug information.

![image](https://cloud.githubusercontent.com/assets/339144/23110623/8fd621a8-f6d7-11e6-9c26-15a74d103a95.png)

Clearly everytime the `/stations` is accessed the following parameters are `None`
* `startTime`
* `endTime`
* `Callsign` 

`timespan` and `nodeId` are default values that are none `None`

The try/except however cause the script to not fail and somewhere the stations are found and APRS is **actively working now!**

Since every call to the `/stations` is failing with type `None` it is clear that this block of code is not actually needed. for operation.

**Comment by kb1lqd** [comment]
Debugging further it is clear that parameters contains type "Nones" as expected entering the `queryStationsDb`

Clearly `queryStationsDb` is providing the data from the database which is why this is now working. Why is this needed? What is the URL callsign/parameters for @kb1lqc ?

![image](https://cloud.githubusercontent.com/assets/339144/23110894/81bb20f8-f6d9-11e6-85c7-57673dd904e7.png)

![image](https://cloud.githubusercontent.com/assets/339144/23110927/bc0a013e-f6d9-11e6-9ce8-e89040373614.png)

OK it is clear also that `queryStationsDb` is providing the stations logged within a set time from the database itself as default parameters. This is why it is failing, the getStations() function needs to place ALL direct argument work in the try/except to fail gracefully when no URL parameters passes. The reason removing .upper() allows the program to work is simple, Nonetype doesn't have a .upper() attribute when no argument supplied and will always fail if tried. The database is then queried for the stations heard in default timespan and returned (correctly).

Due to the `None` in callsign, it only fails when `None` is attempted to .upper()

### Fixing the problem

@kb1lqc I believe I know how to fix!

* Detect when callsign is `None` and don't try to `.upper()` it
* Might want to keep as much of that parsing/actions with the parameters in try/execute as possible

**Comment by kb1lqd** [comment]
@kb1lqc I went back to the master and still tried but getting connection errors with and without .upper(). I need you to review and fix Telemetry and APRS, they seem to be broken from an APRS side.

![image](https://cloud.githubusercontent.com/assets/339144/23114125/01981a2a-f6f2-11e6-80f5-db0aa96ad620.png)

**Comment by kb1lqc** [comment]
Hmm so here's the gist of APRS:
- stations/ returns a list of any callsign-nodeid that have been heard in the last 5 minutes
- querystationsdb() takes in a list of stations and obtains the latest detailed telemetry from each station.

I'll have to look at this on Monday and see what's going on. This worked fine for me when I tested it. Are you sure you're fully configured?

**Comment by kb1lqc** [comment]
OK I am looking into this now @kb1lqd.

h1. telemetry.py

It appears that line 124 hows the root telemetry server response "/" as defaulting to "%" for callsign. This is an SQLite wildcard. Basically "%" for callsign will return anything while "KB1LQ%" will return any database SOURCECALLSIGN that begins with "KB1LQ[a-z,0-9]"

![image](https://cloud.githubusercontent.com/assets/331540/23144057/d78cbafa-f779-11e6-9c55-0957b60963b2.png)

This does not appear on the "/stations" app route:
![image](https://cloud.githubusercontent.com/assets/331540/23144267/41c1bd48-f77b-11e6-9c35-6511d9a17b2f.png)

h1. Investigating
I placed a `print callsign` statement on line 337 of telemetry.py and a `print r.text` on line 89 of aprs.py. Below is my standard and properly configured APRS application on the bottom and the top command prompt being Telemetry.

![image](https://cloud.githubusercontent.com/assets/331540/23144354/d2c7fd52-f77b-11e6-9dae-cb6be181ea6a.png)

It's clear that the `None` type in Telemetry from doesn't seem to matter at least on my machine. It works fine!

Printing out the SQL query when a "None" callsign is presented on [line 607](https://github.com/FaradayRF/Faraday-Software/blob/master/Applications/Telemetry/telemetry.py#L607).

![image](https://cloud.githubusercontent.com/assets/331540/23144807/0af0dce6-f77f-11e6-9730-e6f64fa75570.png)

It doesn't matter if "None" is the callsign, at least once the upper() is removed since that would have failed.

**Comment by kb1lqc** [comment]
BTW @kb1lqd when your APRS application did this:
![image](https://cloud.githubusercontent.com/assets/331540/23145233/d1f18bfe-f781-11e6-9098-1a4fc54e2b68.png)

That's indicative of you not connecting to APRS-IS. So that problem had nothing to do with telemetry. At least in that instance.

**Comment by kb1lqc** [comment]
OK interesting I noticed that if I type the wrong APRS passcode into login.ini (my personal APRS-IS login info for our APRS application) the connection will still proceed nominally

![image](https://cloud.githubusercontent.com/assets/331540/23145449/012d6cc0-f783-11e6-9fee-7b57cbfdfa74.png)

However, no data ever makes it to the APRS-IS server...

![image](https://cloud.githubusercontent.com/assets/331540/23145446/f7a0c724-f782-11e6-9088-0d5d99d5e2d7.png)

**Comment by kb1lqc** [comment]
OK @kb1lqd I pushed updates to my [issue91 branch](https://github.com/FaradayRF/Faraday-Software/commit/1ff5e1a4b4d2999ec1a781df41cdcdf6d4d63cc2) which performs the following.
- Cleaned up telemetry.py upper() statements
- Forced upper() on telemetry callsign URL paramerter get() calls
- Changed callsign default value from "None" to "%" which passes an upper() call and is a valid SQL wildcard
- Removed SQL string generation for callsign = None
- No longer uses login.ini configuration file for APRS, APRS-IS callsign located in aprs.ini now
- Implemented a basic APRS-IS passcode generator. This automatically generates a passcode to protect against simple poor passcode entry and helps remove an extra configuration file.

Created [Pull Request #93](https://github.com/FaradayRF/Faraday-Software/pull/93) with this branch. Please review and approve it if your issues go away.

**Comment by kb1lqc** [comment]
Interesting, as I let the APRS application sit there it eventually stopped. It appears as though APRS-IS forcibly closed my connection. I wonder if it's because of the update rate?

![image](https://cloud.githubusercontent.com/assets/331540/23147299/ad3cb8cc-f792-11e6-86c4-f745b6d27f94.png)

**Comment by kb1lqc** [comment]
Yeah I now fail gracefully but I'll have to see if it's because of the 30 second rate I performed this test on...

![image](https://cloud.githubusercontent.com/assets/331540/23148721/3bb22e62-f79c-11e6-95f8-5a8f1e7a518d.png)

**Comment by kb1lqc** [comment]
OK I changed the time interval to 60 seconds and still received an ERRNO 10054:

![image](https://cloud.githubusercontent.com/assets/331540/23150485/9e516f5e-f7a8-11e6-8392-73dac49cc1f5.png)

At this point it's probably a case where a simply catch of reconnecting to APRS-IS when this error occurs would fix it. However, @kb1lqd what do you feel about Issue #96 where we could connect to APRS-IS and perform APRS functionality using the aprslib.

Honestly I don't care enough about providing a fully implemented APRS suite. Faraday is my main goal and if someone else was passionate about implementing a stable APRS library then I feel we should leverage their work, credit where credit is due, and move on!

**Comment by hdkmike** [comment]
One thing that you can do is:
```
PARAMETERS["CALLSIGN"] = callsign.upper() if callsign else None
```
This essentially only evaluates `callsign.upper()` if the condition (`callsign`) is met. If it's not, it just evaluates to `None`.

**Comment by kb1lqd** [comment]
Mike,

 

Yes, GPS isn’t locked and 0’s are being sent from GPS. We haven’t implemented a default to default location when GPS not present. That could be bad if just randomly switching and better left IMHO sending zero’s. You can set the “GPS Present” bit to 0 and the GPS location will default to the flash config.

 

For RF Telemetry:

 

We were questioned on this already so here’s a quick how to:

I realized that Bryce never put this in his tutorial and I created a planned update to do it: https://github.com/FaradayRF/Faraday-Software/issues/90

 

The Faraday units as shipped are not configured to automatically transmit over RF (no valid Callsign). It’s easy though to get RF telemetry working through device configuration.

 

Following the device configuration tutorial <https://github.com/FaradayRF/Faraday-Software/blob/master/Tutorials/start/configuring-faraday.md>  of the unit you want to transmit RF telemetry beacons (both can simultaneously if desired). Make sure to set the RF telemetry bit to “1” (this is default 0). You can also update the telemetry transmission interval (in seconds). Also, RF power output is relatively low by default (due to possible desense if sitting close on a table), if you like to crank it up the maximum “BOOT_RF_POWER” is 152. Manually power cycle the device to have effect. 

 



 

Expect a more detailed tutorial in the next day or two. Also, that developer tutorial branch I linked might be of interest to jump into the programming side.

 

*	Brent

**Comment by kb1lqd** [comment]
Pull request #93 looks to have fixed the issue! I no longer get errors or crashing program.
